#ifndef GRAPHICS_ERRORS_H
#define GRAPHICS_ERRORS_H

typedef enum Graphics_error
{
    GRAPHICS_OK = 0,
    GRAPHICS_VULKAN_INITIALIZATION,
    GRAPHICS_VULKAN_INSTANCE_CREATE,
    GRAPHICS_VULKAN_NO_INSTANCE_EXTENSIONS,
    GRAPHICS_VULKAN_SURFACE_CREATE,
    GRAPHICS_VULKAN_NO_USABLE_PHYSICAL_DEVICE,
    GRAPHICS_VULKAN_NO_USABLE_QUEUE_FAMILY,
    GRAPHICS_VULKAN_LOGICAL_DEVICE_CREATE,
} Graphics_error;

#endif