#ifndef GRAPHICS_ERRORS_H
#define GRAPHICS_ERRORS_H

typedef enum Graphics_error
{
    GRAPHICS_OK = 0,
    GRAPHICS_VULKAN_INITIALIZATION,
    GRAPHICS_VULKAN_INSTANCE_CREATE,
    GRAPHICS_VULKAN_PRESENTATION_EXTENSIONS,

} Graphics_error;

#endif